<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Desc_transaction_model extends CI_Model
{

    public $table = 'desc_transaction';
    public $id = 'dt_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('dt_id,dt_list_products,dt_total_items,dt_total_weight,dt_packing,dt_total_price,dt_desc,dt_date');
        $this->datatables->from('desc_transaction');
        //add this line for join
        //$this->datatables->join('table2', 'desc_transaction.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('desc_transaction/read/$1'),'Read')." | ".anchor(site_url('desc_transaction/update/$1'),'Update')." | ".anchor(site_url('desc_transaction/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'dt_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('dt_id', $q);
	$this->db->or_like('dt_list_products', $q);
	$this->db->or_like('dt_total_items', $q);
	$this->db->or_like('dt_total_weight', $q);
	$this->db->or_like('dt_packing', $q);
	$this->db->or_like('dt_total_price', $q);
	$this->db->or_like('dt_desc', $q);
	$this->db->or_like('dt_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('dt_id', $q);
	$this->db->or_like('dt_list_products', $q);
	$this->db->or_like('dt_total_items', $q);
	$this->db->or_like('dt_total_weight', $q);
	$this->db->or_like('dt_packing', $q);
	$this->db->or_like('dt_total_price', $q);
	$this->db->or_like('dt_desc', $q);
	$this->db->or_like('dt_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Desc_transaction_model.php */
/* Location: ./application/models/Desc_transaction_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-24 16:33:45 */
/* http://harviacode.com */